# Generated by Django 4.2.7 on 2023-11-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
