# Generated by Django 4.2.7 on 2023-12-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_alter_user_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_picture',
            new_name='profile_pic',
        ),
    ]
