# Generated by Django 4.2.7 on 2023-12-19 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_rename_profile_picture_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(default='Auth/profile_pics/default.png', upload_to='Auth/profile_pics/'),
        ),
    ]
