# Generated by Django 4.2.7 on 2023-11-17 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_customuser_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
    ]
